title: Jean-Baptiste Souvestre
description: "I'm a Front-End Developer from Paris, working at Remotium (Avast Software)."
thumbnail: "https://www.jbsouvestre.com/img/thumb.jpg"

url: https://www.jbsouvestre.com
enforce_ssl: www.jbsouvestre.com

author: 
    name: Jean-Baptiste Souvestre
    email: jbsouvestre@gmail.com
    github: jbsouvestre
    twitter: jbsouvestre
    linkedin: jbsouvestre

production_url: https://www.jbsouvestre.com
base_url: https://www.jbsouvestre.com/
rss_path: /rss.xml
atom_path: /atom.xml

analytics_id: UA-52167935-1

exclude: ["README.md", "Rakefile"]

markdown: kramdom
permalink: pretty
paginate: 3

gems:
  - octopress-autoprefixer

defaults:
    -  
        scope: 
            path: ""
        values:
            layout: "default"